on:
  workflow_dispatch:
  push:
  pull_request:

name: ci

env:
  RUSTFLAGS: -D warnings

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.60.0
      - run: cargo check --all --all-features

  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.60.0
      - run: cargo install wasm-pack --version 0.10.3
      - run: cargo test --all --all-features
      - run: wasm-pack test --node --all

  fmt:
    name: Rust Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.60.0
      - run: rustup component add rustfmt clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features -- --deny warnings
